#!/usr/bin/env python
# --- Header : begin ---
# -*- coding: iso-8859-15 -*-
# generated by mkdb

import wx

# --- Header : end ---

# --- InitBase : begin ---
class MyFrame1(wx.Frame):
    def __init__(self, *args, **kwds):
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
# --- InitBase : end ---

# --- Properties : begin ---
        self.__set_properties()
        self.__do_layout()
        
    def __set_properties(self):
        self.SetTitle("frame_2")
# --- Properties : end ---

# --- Layout : begin ---
    def __do_layout(self):
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        self.SetSizer(sizer_2)
        sizer_2.Fit(self)
        self.Layout()
# --- Layout : end ---


# --- App : begin ---
if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = MyFrame(None, -1, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()
# --- App : end ---
