#!/usr/bin/env python
# generated by mkdb

import wx

# begin App
class MyApp(wxApp):
	# begin OnInit
    def OnInit(self):
        return true
	# end OnInit
# end App

# begin Run
app = MyApp(0)
app.MainLoop()
# end Run
