#!/usr/bin/env python
# generated by mkdb

import wx

# begin BaseFrame
class BaseFrame(wx.Frame):
	# begin __init__
    def __init__(self, *args, **kwds):
        self.__set_properties()
        self.__do_layout()
	# end __init__

	# begin __set_properties
    def __set_properties(self):
	# end __set_properties

	# begin __do_layout
    def __do_layout(self):
	# end __do_layout

# end BaseFrame