#!/usr/bin/env python
# generated by mkdb

import wx

# begin InheritFrame
class InheritFrame(MyFrame1):
	# begin __init__
    def __init__(self, *args, **kwds) :
    	MyFrame1.__init__(self, *args, **kwds)
	# end __init__

	# begin events
	# end events

# end InheritFrame