#!/usr/bin/env python
# generated by mkdb

import wx

# begin InheritedFrame
class InheritFrame(BaseFrame):
	# begin __init__
    def __init__(self, *args, **kwds) :
    	BaseFrame.__init__(self, *args, **kwds)
	# end __init__

	# begin events
	# end events

# end InheritedFrame